---
# install needrestart

- name: install needrestart
  apt:
    pkg: needrestart
    state: present
  become: yes

- name: ensure needrestart config is latest
  template:
    src: "{{ item }}.j2"
    dest: "/etc/needrestart/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - notify.conf
    - needrestart.conf
  become: yes

- name: ensure needrestart ignorelist config include is latest
  template:
    src: "needrestart_ignorelist.conf.j2"
    dest: "/etc/needrestart/conf.d/ignorelist.conf"
    owner: root
    group: root
    mode: 0644
  become: yes
  when: needrestart_ignorelist|d()

- name: configure needrestart mail
  template:
    src: 600-mail.j2
    dest: /etc/needrestart/notify.d/600-mail
    owner: root
    group: root
    mode: 0755
  become: yes

