---
# install needrestart

- name: install needrestart
  apt:
    pkg: needrestart
    state: present
    default_release: "{{ 'jessie-backports' if ansible_distribution_release == 'jessie' else omit }}"

- name: ensure needrestart config is latest
  template:
    src: "{{ item }}.j2"
    dest: "/etc/needrestart/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - notify.conf
    - needrestart.conf

- name: ensure needrestart customisation config is latest
  template:
    src: "{{ item }}.j2"
    dest: "/etc/needrestart/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - needrestart_customisations.conf
  when: needrestart_ignorelist

- name: configure needrestart mail
  template:
    src: 600-mail.j2
    dest: /etc/needrestart/notify.d/600-mail
    owner: root
    group: root
    mode: 0755
